# Generated by Django 4.2.11 on 2024-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitee", "0003_remove_camera_location_camera_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="country_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
